### ISSUE TITLE
Problem running setup:clean

### ISSUE THREAD

**Issue by prateekrastogi** [Sly777/ran#243]
Hi,
Due to some commands like rm, path issues, and environment variables, _npm install && npm run setup:clean_ is not running properly on windows. 
The error I am getting is:

Cleaning RAN! for preparing new project...
Installing dependencies... (This might take a while)

Initialising new repository...C:\Code\Starters\RAN\helper_scripts\CL_commands\__helpers.js:155
          if (_err) throw _err;
                    ^

Error: EEXIST: file already exists, open 'C:\Code\Starters\RAN\pages\index.js'

**Comment by Sly777** [comment]
Hey @prateekrastogi, Thanks for reporting the bug! I will work on this.

**Comment by Sly777** [comment]
I fixed it on Beta branch. Can you try it please @prateekrastogi?

**Comment by prateekrastogi** [comment]
Hi, 
It's working perfectly fine now. Thanks. But, I want to point some issues in package.json which are still present. You need to use "cross-env" for setting environment variables as the current way is incompatible on windows. Also, you need to use "rimraf" instead of rm command in your package.json script.

**Comment by Sly777** [comment]
Yeah, I realized that @prateekrastogi :) Honestly I'm working on Unix systems so It's really possible to get the problem on windows. If it's possible, Can you make PR with your fixes, please? It can be a better solution I think.
